# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - base_joint
      - shoulder_joint
      - arm_joint_12
      - arm_wrist_joint
      - wrist_joint_12
      - wrist_joint_23
    command_interfaces:
      - position
    state_interfaces:
      - position